final products = [
  {
    'id': 1,
    'title': 'Nike Air Max 270',
    'price': 150,
    'image': 'assets/images/shoes_1.png',
    'color': 0xFFAEAEAE,
    'brand': 'Nike',
    'size': [7, 8, 9, 10, 11],
  },
  {
    'id': 2,
    'title': 'Adidas Ultraboost',
    'price': 180,
    'image': 'assets/images/shoes_2.png',
    'color': 0xFF000000,
    'brand': 'Adidas',
    'size': [7, 8, 9, 10, 11],
  },
  {
    'id': 3,
    'title': 'Puma RS-X',
    'price': 120,
    'image': 'assets/images/shoes_3.png',
    'color': 0xFFFFFFFF,
    'brand': 'Puma',
    'size': [7, 8, 9, 10, 11],
  },
  {
    'id': 4,
    'title': 'Reebok Classic',
    'price': 100,
    'image': 'assets/images/shoes_4.png',
    'color': 0xFFB22222,
    'brand': 'Reebok',
    'size': [7, 8, 9, 10, 11],
  },
  {
    'title': 'New Balance 574',
    'price': 130,
    'image': 'assets/images/shoe5.png',
    'color': 0xFF808080,
    'brand': 'New Balance',
    'size': [7, 8, 9, 10, 11],
  },
  {
    'title': 'Asics Gel-Kayano',
    'price': 160,
    'image': 'assets/images/shoe6.png',
    'color': 0xFF1E90FF,
    'brand': 'Asics',
  },
  {
    'title': 'Converse Chuck Taylor',
    'price': 90,
    'image': 'assets/images/shoe7.png',
    'color': 0xFFFFA500,
    'brand': 'Converse',
  },
  {
    'title': 'Vans Old Skool',
    'price': 80,
    'image': 'assets/images/shoe8.png',
    'color': 0xFF00008B,
    'brand': 'Vans',
  },
  {
    'title': 'Under Armour HOVR',
    'price': 140,
    'image': 'assets/images/shoe9.png',
    'color': 0xFF228B22,
    'brand': 'Under Armour',
  },
  {
    'title': "Jordan Air Jordan 1",
    'price': 200,
    'image': "assets/images/shoe10.png",
    "color": 0xFFFF4500,
    "brand": "Jordan",
  },
];
